[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group }}

{% for commit in commits %}
- {{ commit.message }} by @{{ commit.author.name }}
{% endfor %}
{% endfor %}
"""

footer = ""

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"

commit_parsers = [
    { message = "^feat", group = "ğŸš€ Features" },
    { message = "^fix", group = "ğŸ› Bug Fixes" },
    { message = "^refactor", group = "ğŸšœ Refactor" },
    { message = "^perf", group = "âš¡ Performance" },
    { message = "^docs", group = "ğŸ“š Documentation" },
    { message = "^test", group = "ğŸ§ª Tests" },
    { message = "^chore\\(deps\\)", group = "ğŸ“¦ Dependency Updates" }
]

group_order = [
    "ğŸš€ Features",
    "ğŸ› Bug Fixes",
    "ğŸšœ Refactor",
    "âš¡ Performance",
    "ğŸ“š Documentation",
    "ğŸ§ª Tests",
    "ğŸ“¦ Dependency Updates"
]