[tasks.lint]
run = "cargo clippy --all-targets --all-features"

[tasks.release]
run = "cargo build --release"

[tasks.build]
run = "cargo build"

[tasks.ios]
run = "cargo run project sample/sample.xcodeproj sample 26.2 17 generate-file"

[tasks.test]
run = "cargo test"

[tasks.check]
run = "cargo check"

[tasks.doc]
run = "cargo doc --no-deps"

[tasks.fmt]
run = "cargo fmt --all -- --check"